### ISSUE TITLE
Trying to update multi-line text references a missing object

### ISSUE THREAD

**Issue by Tom-Kingstone** [BHoM/PowerPoint_Toolkit#14]
#### What is missing/incorrect?

When trying to update text with SimpleTextUpdate, and the element in the slide has multiple paragraphs, then an error is recorded as follows: 
`The element contains more than one line of text. Please use MultiLineTextUpdate for this.`

The MultiLineTextUpdate object does not currently exist, and this causes confusion to users.

To fix, either:
* Implement MultiLineTextUpdate

or
* Replace the error with something like: `The element contains more than one line of text. Updating multiple lines of text is not currently supported with SimpleTextUpdate.` or similar

**Comment by IsakNaslundBh** [comment]
Going to close this as tackling the issue in https://github.com/BHoM/PowerPoint_Toolkit/issues/15
